version: '2'
services:
  zookeper:
    build: zookeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
  
  broker:
    build: broker
    depends_on:
      - zookeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ZOOKEEPER_CONNECT: zookeper:2181

  streamer:
    build: streamer
    depends_on:
      - broker
    environment: 
      KAFKA_BROKER: broker:9092
  
  hadoop_hive:
    build: hadoop_hive
    depends_on: 
      - streamer
    ports:
      - 9000:9000
      - 9083:9083
    environment: 
      HADOOP_PORT: 9000
      HIVE_PORT: 9083

  spark:
    build: spark
    depends_on: 
      - streamer
      - hadoop_hive
    environment:
      KAFKA_BROKER: broker:9092
      HIVE_SERVER: hadoop_hive:9083

